### ISSUE TITLE
server dasn't start

### ISSUE THREAD

**Issue by Baioretto** [Katharsas/GMM#136]
Error creating bean with name 'dataBaseInit' defined in file [C:\Users\aaa\Downloads\Compressed\apache-tomcat-9.0.73\apache-tomcat-9.0.73\webapps\GMM\WEB-INF\classes\gmm\service\data\DataBaseInit.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'backupAccessService' defined in file [C:\Users\aaa\Downloads\Compressed\apache-tomcat-9.0.73\apache-tomcat-9.0.73\webapps\GMM\WEB-INF\classes\gmm\service\data\backup\BackupAccessService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'backupFileService' defined in file [C:\Users\aaa\Downloads\Compressed\apache-tomcat-9.0.73\apache-tomcat-9.0.73\webapps\GMM\WEB-INF\classes\gmm\service\data\backup\BackupFileService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'XMLService' defined in file [C:\Users\aaa\Downloads\Compressed\apache-tomcat-9.0.73\apache-tomcat-9.0.73\webapps\GMM\WEB-INF\classes\gmm\service\data\xstream\XMLService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [gmm.service.data.xstream.XMLService]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError 
09:16:55.284 [      main] ERROR o.s.web.context.ContextLoader - Context initialization failed

**Comment by Katharsas** [comment]
I fixed this in the code some time ago but there is no release for it yet, I will make one where this should be fixed.

**Comment by Katharsas** [comment]
Let me know if the new release works:
https://github.com/Katharsas/GMM/releases/tag/1.0.3-SNAPSHOT

**Comment by Baioretto** [comment]
Progress
[image: obraz.png]


śr., 22 mar 2023 o 00:31 Jan ***@***.***> napisał(a):

**Comment by Katharsas** [comment]
If you tried to upload a picture, i cannot see it.

**Comment by Katharsas** [comment]
i assume this is solved, reopen otherwise
