### ISSUE TITLE
Integrate SVN for new assets

### ISSUE THREAD

**Issue by Katharsas** [Katharsas/GMM#78]
- listen for svn commit and update data
- commit on upload
- prevent deletion of asset tasks with existing assets

**Comment by ThielHater** [comment]
Fuck yeah!

**Comment by Katharsas** [comment]
Continued in 939a255

**Comment by Katharsas** [comment]
TODO: Test commit on upload

**Comment by Katharsas** [comment]
TODO:
Add CSS for folder creation dialog and and add vertical scroll for big file tree view.
