### ISSUE TITLE
I can't start project without problems

### ISSUE THREAD

**Issue by arturkasperek** [Katharsas/GMM#95]
<img width="1440" alt="zrzut ekranu 2018-05-05 o 00 25 55" src="https://user-images.githubusercontent.com/6894763/39655863-6cc78e3e-4ffc-11e8-948d-6b47699a9849.png">
After starting project I see that wired signs, how to fix that ?

**Comment by Katharsas** [comment]
Looks like it it doesnt find the language files. Which browser do you use, which GMM version (latest?) and did you use the appRun command to start it or a custom container?

**Comment by Katharsas** [comment]
I reopen if this is still a problem.
